### ISSUE TITLE
Behavior inconsistency with `request` re: `tough-cookie` integration

### ISSUE THREAD

**Issue by ScottyMJacobson** [request/request-promise#183]
Normally I'd try to dig more for an explanation, but I'm a bit confounded here. I'm doing some cookie construction / management by hand via `tough-cookie` to maintain sessions for my API calls, and it looks like `request` and `request-promise` are giving me two different behaviors, where `request` works but `request-promise` does not.

The problematic code is as follows

```
const request = require('request');
const requestPromise = require('request-promise');
const tough = require('tough-cookie');

let sessionCookie = new tough.Cookie({
    key: "some_key",
    value: "some_value",
    domain: 'api.mydomain.com',
    httpOnly: true,
    maxAge: 31536000
});
let cookiejar = request.jar();
cookiejar.setCookie(sessionCookie, 'https://api.mydomain.com'); // does not throw an error


let sessionCookie2 = new tough.Cookie({
    key: "some_key",
    value: "some_value",
    domain: 'api.mydomain.com',
    httpOnly: true,
    maxAge: 31536000
});
let cookiejar2 = requestPromise.jar();
cookiejar2.setCookie(sessionCookie2, 'https://api.mydomain.com'); // TypeError: str.trim is not a function
```

Is it just a version/dependency thing? Am I just abusing the concept of cookie jars beyond repair?
From my package.json:
```
    "request": "^2.81.0",
    "request-promise": "^4.2.0",
    "tough-cookie": "^2.3.2",
```

I'm leaving the `request.jar()` patch in for now, but I'd love to know what's going wrong exactly

Thanks in advance,
Scotty

**Comment by analog-nico** [comment]
Thanks for making it easy for me to reproduce the issue @ScottyMJacobson ! This one haunted me a while back already.

When you use `request-promise` there are two different `Cookie` prototypes in play and `tough-cookie` derails. There is nothing you can do. I am working on a fix inside of `request-promise`.

**Comment by analog-nico** [comment]
I just published `request-promise@4.2.1` which includes the fix. Thanks again for bringing this up!

**Comment by frejus123** [comment]
Now I am trying to use request-promise@4.2.1  to generate cookiejar
 like let cookiejar2 = requestPromise.jar();  but it still occur this problem,why?

thanks a lot

**Comment by analog-nico** [comment]
@frejus123 Could you post your code snippet to help me understand your situation?

**Comment by analog-nico** [comment]
@frejus123 If you use the same code as shown in the README then most likely you have `tough-cookie` installed multiple times. Please run `npm ls tough-cookie` to verify that and make sure you have it installed only once.

**Comment by frejus123** [comment]
Thanks analog-nico a lot.By using npm ls tough-cookie:

├─┬ request-promise@4.2.1
│ └── tough-cookie@2.3.2     (A)
└── tough-cookie@2.3.2        (B)

 I found I really have installed tough-cooke twice,then I delete one tough-cookie marked as (B).
When I run again ,it occur  tough is not defined



`
var rp = require('request-promise');
 var cookie = new tough.Cookie({
            key: tssKey,
            value: tssVal,
            //domain: 'localhost',
            httpOnly: true,
            maxAge: 31536000
        });
        var cookiejar = rp.jar();
        cookiejar.setCookie(cookie, 'http://localhost:8080');
        var requestOptions = {
            method: 'POST',
            uri: 'http://localhost:8080/ruyimadepot/invoke'+postUrl,
            body:jsonStr,
            headers: {
                'content-type': 'application/json;charset=UTF-8'
            },
            //resolveWithFullResponse: true,
            jar: cookiejar
        };`

**Comment by analog-nico** [comment]
@frejus123 If you delete A instead of B then it should work. This then also resembles the packages hierarchy when you do a clean `npm install`.

**Comment by frejus123** [comment]
@analog-nico 
Thanks a lot, it's resolved. #

**Comment by analog-nico** [comment]
@frejus123 Excellent. I'll add a note to the README for people who experience the same issue as you just did. Happy coding!

**Comment by kapilchokhawala** [comment]
I am having the same problem as @ScottyMJacobson I am using exactly same code. 
![screen shot 2018-05-24 at 4 34 15 pm](https://user-images.githubusercontent.com/1270533/40518669-9c7cd250-5f70-11e8-9926-3b211adf615c.png)

**Comment by ScottyMJacobson** [comment]
Like @kapilchokhawala, I started getting this error again (I'm not sure whether it was triggered by a new version of one of the relevant packages). This time, the error happened even when I used `let jar = request.jar();` (which seems to have been the workaround I had found last year, using the non-promise request lib)

The solution over in [this `request` issue thread](https://github.com/request/request/issues/1939) seemed to have worked, but feels a bit brittle to dig into the internals of request / tough-cookie

```
            let toughCookieJar = new tough.CookieJar(undefined, {looseMode: true});
            let jar = request.jar();
            jar._jar = toughCookieJar;
            jar.setCookie(cookieObject, endpoints.base);
```

**Comment by mfonsen** [comment]
I bumped into this problem, solved by downgrading packages for now:
```
    "request": "^2.85.0",
    "request-promise": "^4.2.2",
    "tough-cookie": "^2.3.4"
```

**Comment by ScottyMJacobson** [comment]
@mfonsen after some poking around with versions, it looks like for me as well tough-cookie 2.3.4 (and the others) are the last version that I can get to work

@analog-nico this appears to have broken the unit tests for this lib and `requests-promise-native` (the lib we're actually using) - let me know if you'd like me to open an issue in that repo as well

**Comment by milespoindexter** [comment]
I'm also getting the same error msg after upgrading from 2.3.4 to 2.4.2:
TypeError: str.trim is not a function

**Comment by guillaumegarcia13** [comment]
Same here with this
```const cookieDetails = new tough.Cookie({ ... });
const cookieJar = rp.jar();
const cookie: request.Cookie | string = request.cookie(cookieDetails.toString()) || '';
cookieJar.setCookie(cookie, `https://${ domain }`);
```

Yet, replacing the last 2 lines with:
```cookieJar.setCookie(cookieDetails.toString(), `https://${ domain }`);```

seems to solve this.

**Comment by HELLKING66666** [comment]
The problem is not solved yet.

---

+-- request@2.83.0
| `-- tough-cookie@2.3.4
+-- request-promise@4.2.1
| `-- tough-cookie@2.4.2  deduped
`-- tough-cookie@2.4.2

**Comment by fXy-during** [comment]
> cookieJar.setCookie(cookie.toString(), `https://${ domain }`);
toString(). It's work for me

**Comment by josephgruber** [comment]
Clean install, using the exact code from the example, and this still occurs for me

**Comment by uct8086** [comment]
i just fixed like this:

    let cookie = new tough.Cookie({
            key: "key",
            value: value,
            domain: 'http://test.com',
            httpOnly: true,
            maxAge: 31536000
        });
        let cookie_str = cookie.toString();

        cookie_str = cookie_str.replace('Domain=http://test.com;', '');

        let cookiejar = rp.jar();
        cookiejar.setCookie(cookie_str, 'http://test.com');


it worked.  ^V^
